# Site settings
title: Daniel Wayhs
email: danielwayhs@gmail.com
description: >
  This is my personal website. Here you can find information about me, my work and other passions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://daniel.wayhs.me"
twitter_username: dwayhs
github_username:  dwayhs

# Build settings
markdown: kramdown

google_universal_analytics: UA-62265210-1
google_universal_analytics_cookiedomain: auto

gems:
  - octopress-escape-code

headers:
  - filename: '^assets.*\.js$'
    expires: '+3 years'
    cache_control: 'max-age=94608000'
    content_type: 'application/javascript'
  - filename: '^assets.*\.css$'
    expires: '+3 years'
    cache_control: 'max-age=94608000'
    content_type: 'text/css'
